### ISSUE TITLE
Add ping_*() functions to check if APIs are running

### ISSUE THREAD

**Issue by EDiLD** [ropensci/webchem#118]
From a reviewer:

> Some of the man pages I looked at indicated that the query might fail if the API is unavailable. It might be useful to have a helper method to test the availability of the remote resource before the query is run.

- [ ] allanwood
- [ ] chemid
- [ ] chemspider API
- [x] chemspider web page
- [ ] cir
- [ ] cts
- [ ] etox
- [ ] opsin
- [x] pan
- [ ] physprop
- [x] pubchem
- [ ] wikidata

**Comment by Krisselack** [comment]
Using cir_query on a char-vector sometimes resulted for me in the following error: 
"Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached"
The problem was, that no NA was returned in that case and the sequence got messed up.

**Comment by EDiLD** [comment]
Thx for reporting this. I couldn't reproduce this and it *should* return NA in case of a timeout.

It basically implemented like this:

```r
library(httr)
h <- try(GET("http://httpbin.org/delay/3", timeout(1)))
if(inherits(h, 'try-error')) NA
```

Can you provide a reproducible example?

**Comment by Krisselack** [comment]
I don't know how reproducible it is, but after running this script it occured a few times. 
To save time, now I query for unique entries... strangely, without that error. 

[chems.txt](https://github.com/ropensci/webchem/files/541872/chems.txt)
chems <- read.csv("chems.txt",stringsAsFactors = FALSE)
chems[which(chems=="PAK 16")] <- "PAK_16"
chem_namen <- cir_query(chems,'names',first=TRUE)

**Comment by stitam** [comment]
I see that we currently export `ping_cs()`, `ping_pan()`, `ping_pubchem()`, `ping_pubchem_pw()`. I was wondering how this will look like when we implement `ping_*()` functions for all web services and also add 10 more web services;). Also @Aariq introduced the `is.down()` functionality for tests in #248 which is very similar to `ping()`. Maybe we could export only one `ping()` function which calls various non-exported ping functions internally and use this function in the tests as well? Would this make things more simple/consistent?

**Comment by Aariq** [comment]
A simple change that I can imagine being helpful is changing it to just `ping_service(service)` where service is the prefix for the functions for that service. Then, when a new service is added, we just need to add a URL to a `switch()` statement or something like that.

**Comment by stitam** [comment]
So you suggest a single exported `ping_service()` function which uses `switch()` to switch between urls internally, depending on the service, e.g `ping_service("cs")`, `ping_service("pc")`, etc., right? I think this could work for most services. Also if a web service is more tricky than that, we can still call it from within `ping_service()` so it doesn't have to be exported.

**Comment by Aariq** [comment]
That sounds good to me.  Shall I do this as part of #248?

**Comment by stitam** [comment]
It's better not to export new functions in the first place, so if you have time for this, it would be great!
