### ISSUE TITLE
Add NEWS for CRAN release in Releases tab please

### ISSUE THREAD

**Issue by sckott** [ropensci/webchem#122]

**Comment by sckott** [comment]
also, it's not clear what was changed in the most recent cran version, i don't see any news items for it

**Comment by EDiLD** [comment]
I have not prepared a release on github. 
Thx for the pointer.
News can be found [here](https://cran.r-project.org/web/packages/webchem/NEWS).
Sorry for wrong/additional versioning...

**Comment by EDiLD** [comment]
Release now on [github](https://github.com/ropensci/webchem/releases/tag/v0.1.1).

**Comment by sckott** [comment]
No problem, but that doesn't match the version that's on CRAN `v0.1.1.1`

**Comment by EDiLD** [comment]
I stripped of the last .1...
Have to read some lessons regarding versioning...
@sckott is there a function to autoincrement the 4th digit?

**Comment by sckott** [comment]
We generally follow http://yihui.name/en/2013/06/r-package-versioning/ 

basically:

* `x.y.z` versions can go to CRAN - usually shoot for going to CRAN when the `y` part increments, but `z` increments are sometimes required for bug fixes, etc. 
* can add 4th place `x.y.z.b` for dev versions on github, i often do e.g., `0.1.0.9000` and increment the what i call `dev version` when making small changes, then increment the patch version when changes are big enough to warrant it
