### ISSUE TITLE
cs_prop throws error with some CSIDs

### ISSUE THREAD

**Issue by Aariq** [ropensci/webchem#127]
cs_prop() seems to not work with certain CSIDs

For example `cs_prop(16105)` yields:

> NAs introduced by coercionError in data.frame(prop, value_pred, unit_pred, source_pred, value_exp,  :   arguments imply differing number of rows: 7, 5, 6

Other examples of CSIDs that give a similar error:
- 9912
- 13876539
- 7889
- 11885
- 73261
- 28985

**Comment by Aariq** [comment]
Some of the problems are caused by missing values in the EPI properties and dealt with those, but there are also situations where there are multiple values for some properties.  E.g. csid 7812 has two water solubility estimates.

**Comment by EDiLD** [comment]
Thank you for your valuable contribution and extensive checking!
I will have a look at it and merge the pull request by the end of the next week.

**Comment by Aariq** [comment]
FYI it doesn't totally fix the problem.  Occasionally there is more than
one entry for a particular property and that still causes it to fail.  A
possible temporary fix is adding an option to only get ACD values (which
work fine), but I'm not familiar enough with writing functions to know how
to do that off the top of my head.

-Eric

**Comment by EDiLD** [comment]
Commit c6d8089 fixes this bug and passes all tests with the above mentioned CSID.

`cs_prop` is currently a bit messy...
- [ ] Currently experimental BP and MP are ignored
- [ ] Other fields returned by EPISuite are also ignored and should be incorporated.

**Comment by EDiLD** [comment]
In master branch now.
