### ISSUE TITLE
use menu() to select from synonyms in pc_synonyms()?

### ISSUE THREAD

**Issue by Aariq** [ropensci/webchem#129]
the `pc_synonyms()` function currently returns a list of all the synonyms for every query provided.  I'm currently using this function to find "prettier" names for compounds for a publication, so I don't want _every_ synonym, just the "best" looking one. 

I've written a for loop that does this with CIDs and original ("ugly") names using `menu()`

Is this something that could be implemented as an option for `pc_synonyms()` or as a separate function aimed at specifically getting "pretty" names?

```
#number of synonyms to return in the menu
n <- 20

pretty.names <- 1:length(CIDs)

for(i in 1:length(CIDs)){
  if(is.na(CIDs[i])){
    pretty.names[i] <- NA
  }else{
  synonyms <- c(ugly.name[i], pc_synonyms(CIDs[i], from = "cid")[[1]][1:n])
  choice <- menu(c(synonyms), title = ugly.name[i], graphics = TRUE)
  pretty.names[i] <- synonyms[choice]
  }
}
```

**Comment by EDiLD** [comment]
Thanks for this suggestion!

Hmm, either we could add an argument `interactive` to pc_synonyms which enters this interactive mode.
Or we define a [Function operator](http://adv-r.had.co.nz/Function-operators.html) that can be called and add this to pc_synomyns.
Don't know which way is best... Will think about it...
Good luck with your paper!

**Comment by EDiLD** [comment]
Thanks for your suggestion. `synonyms` gained an argument `interactive=<x>` to pick interactively 1 out of <x> synonyms.

**Comment by Aariq** [comment]
awesome, thanks!
