### ISSUE TITLE
Extract additional data chemspider

### ISSUE THREAD

**Issue by EDiLD** [ropensci/webchem#132]
- [ ] Additional names
- [ ] Add also indicator for type (e.g [RN])
- [ ] Additional properties
- [ ] Some field from EPI-Suite are currently ignored, add those.

**Comment by Aariq** [comment]
I think we can close this, yeah?  Unless there is more info we could get from the ChemSpider API (not web scraping, as they forbid it).

**Comment by stitam** [comment]
One thing that hasn't been implemented yet is images. I'll add `cs_image()` and then we can close this issue.
