### ISSUE TITLE
Getting vapor pressure from EPI suite in Chemspider

### ISSUE THREAD

**Issue by ghost** [ropensci/webchem#135]
I was wondering if there is a possibility to add a function to retrieve the vapor pressure from EPI suite? I find that ACD cannot give good predictions for compounds with low VP.
Thanks for a great package.

**Comment by EDiLD** [comment]
This is already reported as enhancement here: #132 .
I currently do not have free resources to work on this. PRs are highly welcome!

**Comment by Aariq** [comment]
@stitam is this something that you are working on, or is this no longer possible since we aren't scraping ChemSpider anymore?

**Comment by stitam** [comment]
One of the ChemSpider APIs returns external references for ChemSpider records. I haven't looked into it yet, but it might allow us to access EPI suite data.

**Comment by stitam** [comment]
I have looked into it, I think this is no longer possible with ChemSpider. I will try to find an alternative.
