### ISSUE TITLE
Point separator missing from queried numbers.

### ISSUE THREAD

**Issue by stanstrup** [ropensci/webchem#137]
Example:  `pp_query("111-27-3")`.

You get a boiling point of 1576 that should be 157.6.

PR with a fix here: https://github.com/ropensci/webchem/pull/136

**Comment by EDiLD** [comment]
Thanks for reporting this and the PR. 
I'll take a look ASAP (likely on weekend).

**Comment by EDiLD** [comment]
Closed via https://github.com/ropensci/webchem/commit/28f3f0701927905348571b651eed3e69ebc06b52.
