### ISSUE TITLE
Handle missing epiSuite data on chemspider

### ISSUE THREAD

**Issue by stanstrup** [ropensci/webchem#139]
Some CS records are missing epiSuite data.

Example here: https://www.chemspider.com/Chemical-Structure.21106900.html

The parsing for those will fail.

I added a fix to the PR here: #136
I hope that is OK.

**Comment by EDiLD** [comment]
Please use separate PRs per issue. [Will cherry-pick it for now].

**Comment by stanstrup** [comment]
Yes sorry about that. I was in a hurry and needed something with all the fixes to finish something.

Thanks for dealing with it this fast.

**Comment by EDiLD** [comment]
No problem. Note, that I also turned all your issues into tests (ensuring this will newer come up again).
