### ISSUE TITLE
Scientific notation number handled incorrectly

### ISSUE THREAD

**Issue by stanstrup** [ropensci/webchem#143]
Example here: http://www.chemspider.com/Chemical-Structure.391783.html
`Water Solubility at 25 deg C (mg/L):  1.369e+004`
is read as 1.369.

**Comment by stanstrup** [comment]
Maybe you have to be explicit and do something like

```r
grep('Water Solubility at 25 deg C', ll, value = TRUE) %>% 
sub('Water Solubility at 25 deg C (mg/L):',"", ., fixed=TRUE) %>% 
as.numeric
```

**Comment by EDiLD** [comment]
Thanks @stanstrup  for reporting.
I added some regex to capture scientific notation in EPI-Suite output (very messy stuff...)

```r
m4 <- cs_prop(391783)
r <- m4$`391783`$epi
r$value_pred[r$prop == 'Water Solubility from KOW']
# [1] 13690
```

**Comment by stanstrup** [comment]
Thanks!
