### ISSUE TITLE
FooDB

### ISSUE THREAD

**Issue by Aariq** [ropensci/webchem#145]
[FooDB](http://foodb.ca/) has a lot of great information, but rather than providing an API, it provides a download of either a folder of .csv files or a SQL file.  The folder of .csv files takes up about 440 MB, and the SQL file is about the same size. Would you be opposed to functions that require a path to this folder of .csv files as an argument?  Or are you committed to the "web" in "webchem"?

**Comment by EDiLD** [comment]
Fine with me. Would prefer the SQL source over csv. Can you also implement a function to download/setup the database?
Do you need/want full access to this repository (no need for PRs)?

**Comment by Aariq** [comment]
I'll have to learn some things about SQL before I can do that.  I don't know that I want full access.  That feels like too much responsibility!

**Comment by EDiLD** [comment]
Cool, thanks.
csv is also fine if that's easier.

Mit AquaMail Android
http://www.aqua-mail.com gesendet


Am 4. März 2018 11:01:32 PM schrieb Eric R Scott <notifications@github.com>:

**Comment by Aariq** [comment]
It's working for me @Automation-projects-2025: https://foodb.ca/downloads

**Comment by stitam** [comment]
I'll keep this issue open for a bit longer. I implemented offline access to FooDB but I want the structure of `foodb_query()` responses to look more like the online pages (e.g. https://foodb.ca/compounds/FDB000004). The data is essentially there but not in the right order, etc.
