### ISSUE TITLE
Scraping GC retention indices from NIST

### ISSUE THREAD

**Issue by Aariq** [ropensci/webchem#152]
It would be amazing if there was a function to get literature retention indices from webbook.nist.gov using CAS numbers or other identifiers.  I'd be happy to work on this function, but would love some feedback on how it would work first. Right now I'm thinking there would be an argument for CAS numbers, and maybe the following options:

1. An option to choose which type of RI. webbook.nist.gov has three different retention indices: Kovats, Normal Alkane, and Van Den Dool and Kratz. 
2. An option for polar or non-polar column.
3. An option to specify column types (e.g. DB-5, Supelcowax-10, etc.)
3. This would sometimes match many different literature RIs.  An option to return an average, or all of them (as a data frame with reference and comments).
4. Possibly some way of prioritizing the above arguments?  For example, if a Van Den Dool and Kratz RI isn't listed, get the Normal Alkane one.

I'd love to hear thoughts and feedback.

**Comment by EDiLD** [comment]
I've found some info on the net:

* https://stackoverflow.com/questions/20004779/importing-data-associated-with-a-given-cas-number-from-the-nist-webbook-web-site
* https://mathematica.stackexchange.com/questions/37091/look-up-info-associated-with-a-given-cas-chemical-identifier-from-the-nist-webbo/37189#37189
* https://gist.github.com/mcs07/48fcfc0f072e5f45dcaa

They seem to not provide an API :( - So you need to go the web-scraping way...

Please be nice to the server (restrict the calls to 3/second or choose from a gamma distribution, to avoid getting blocked).
Some xpath (via xml2 package) is definitively beneficial. 
See `chemid.R` and `pan.R` here for examples (code is quite old, newer methods might be available).
[hmtltidy](https://hrbrmstr.github.io/htmltidy/) mitght be also useful for development.

Hope this helps,

Edi

**Comment by EDiLD** [comment]
Related PR: https://github.com/ropensci/webchem/pull/154

**Comment by EDiLD** [comment]
@Aariq This can be closed, as now implemented by you?

**Comment by Aariq** [comment]
yes, it can be closed.
