### ISSUE TITLE
Wanted: Maintainer

### ISSUE THREAD

**Issue by EDiLD** [ropensci/webchem#155]
I am not using webchem actively and I can't bring up the time that webchem deserves anymore.

I am looking for a maintainer & developer to take over.
@sckott, do you know of anybody from the ropensci community?
Anyone of the contributor interested @jranke, @Aariq, @Dahaniel 

If I can't find someone till end of year, webchem will be abandonware without [maintenance ](http://unmaintained.tech/). 
I'd really like to see webchem in good and motivated hands...

**Comment by adelenelai** [comment]
I'm interested in developing but frankly have no formal experience. Ready to learn.

**Comment by EDiLD** [comment]
@Aariq I understand stand that.  Better focus on finishing your PhD.
@adelenelai I am also no formal programmer (eventually I became one through the years). You just need to know R and be motivated (that's most important) . The rest (unit testing, code quality, cran submissions, ...) than comes from alone...

**Comment by EDiLD** [comment]
@andreasLD Maybe someone from the Landau-gang interested?

**Comment by sckott** [comment]
we (ropensci) are happy to help whoever decides to take this on - The piont is: you are not alone! 

@EDiLD I don't know of anyone one right now. Ideally it would be someone that knows the subject area and will use it themselves - and we can help with technical bits if needed. We can do a call out in Slack as well.

**Comment by lzyacht** [comment]
Hi there! Me and my colleagues would be interested in potentially being the maintainer for this package. We are part of a metabolomics lab and regularly use chemical information. We have experts in chemistry and in R package development. Can we discuss in more detail via e-mail? I can send some more information to your available e-mail addresses. Thank you!

**Comment by andreasLD** [comment]
Hi @EDiLD ,
generally I would be interested and I have had a deeper look in some of the functionality but I should also not spent too much time on side-projects next to finishing the PhD. @KunzstLD are you maybe interested as well?

**Comment by KunzstLD** [comment]
Hey @EDiLD & @andreasLD , 
I'm definitely interested but I'm also not sure if I have the required skills (though I have a bit of experience in R). Happy to talk about this with you @EDiLD.

**Comment by allaway** [comment]
Hi there, 

I do not have the time to commit to being a maintainer but I am interested in contributing. I'd would be happy to discuss with whoever ends up being the maintainer to see where I can best help. I have a decent working knowledge of R and cheminformatics but have not spent much time looking at the `webchem` codebase.

**Comment by Aariq** [comment]
I think the first priority issue is #149, switching to the new chemspider API.  Currently all the chemspider related functions are broken. :-(.  So if you have some experience with APIs or are willing to learn, I think that would be the place to start probably!

**Comment by allaway** [comment]
Hi @Aariq - Thanks for following up. I was also affected by the chemspider API switch, so I'll see if I can make any progress there.

**Comment by EDiLD** [comment]
Thank you @allaway for your  contribution!
