### ISSUE TITLE
cs_inchi_smiles() function only returns NA

### ISSUE THREAD

**Issue by reventropy** [ropensci/webchem#160]
inchi = cs_inchikey_inchi("AAMAQVCMQYBDCZ-UHFFFAOYSA-N")
smiles = cs_inchi_smiles(inchi)
print(inchikey)
print(inchi)
print(smiles)

This prints:
"InChI=1S/C27H24N2O4/c1-3-32-27(30)26-22(16-31-2)25-21-13-19(11-12-23(21)29-24(25)14-28-26)33-15-18-9-6-8-17-7-4-5-10-20(17)18/h4-14,28H,3,15-16H2,1-2H3"
"NA"

The same is true for all inchikeys I've tried.  The web interface returns:

CCOC(=O)c1c(COC)c2c3cc(ccc3nc2c[nH]1)OCc1cccc2ccccc12

instead of NA

**Comment by EDiLD** [comment]
Old chemspider api is deprecated & new one not implemented. Help wanted! See also https://github.com/ropensci/webchem/issues/149
