### ISSUE TITLE
nist_ri() fails with large numbers of compounds

### ISSUE THREAD

**Issue by Aariq** [ropensci/webchem#166]
I haven't tested this or reproduced it, but a commenter on a [blog post](http://www.ericrscott.com/2018/06/28/webchem/#disqus_thread) experienced an error when trying to retrieve retention indices for 500 compounds.  The error read `Error in open.connection(): Timeout was reached.`  They did not experience this when getting 100 compounds at a time.  Might just need additional sys.sleep() or perhaps I could make use of the `polite` package.

**Comment by Sukis123** [comment]
Hi Aariq, how is it going? I still have this problem when I work with more than 500 compounds. I am new in R, could you please give me an example of using sys.sleep() or polite package?

thank you very much.

**Comment by Aariq** [comment]
This is something that I need to implement internally in the code for the `nist_ri()` function.  In the meantime, I'd suggest splitting your data into smaller pieces and then using something like `dplyr::bind_rows()` to combine the resulting dataframes.

**Comment by Sukis123** [comment]
understand, thank you very much.

**Comment by Sukis123** [comment]
@Aariq Hi Aariq, I just come up a question today. My lab have a NIST14 library for GC-MS. I want to prepare a NIST14.MSP file together with RI information for MS-DIAL identification. Doing so, the identification can be done automatically to some extent. However, there is no RI information in the MSP file using lib2nist tool. I am currently trying to retrieve RI information using webchem, but there are huge amount of compounds in the NIST 14. It is a good idea for me, however,  I am just not sure if it is ok regarding legality since i am trying to scrap RI for numerous compounds??

**Comment by Aariq** [comment]
You should probably not be using webchem() to download RIs for all the compounds in NIST14.

**Comment by Ahmedserag777** [comment]
@Aariq I am trying the same approach as @Sukis123 Unfortunately, Igot this error and my loop stopped "Error in open.connection(x, "rb") : 
  schannel: next InitializeSecurityContext failed: SEC_E_MESSAGE_ALTERED (0x8009030F) - The message or signature supplied for verification has been altered"   
Is it any way to retrieve the RI from the NIST08 directly without webchem?
Thanks

**Comment by Aariq** [comment]
This bug may have been fixed as the timings have changed in the development version, but I'm reluctant to test with 500+ compounds.  Also, a simple workaround is to split your data into chunks of less than 100 compounds and then `dplyr::bind_rows()` on the results.  Here's an example assuming you have a vector of identifiers:

```
library(webchem)
library(purrr)
library(dplyr)

cas  #pretend these are your CAS#s in a vector of length 500.
groups <- factor(rep(1:5, each = 100)) #split into 5 groups of 100
output <-
  split(cas, groups) %>% #splits vector into list
  map(~nist_ri(.x, from = "cas")) %>% #maps over list
  bind_rows() #combines resulting dataframes

```
