### ISSUE TITLE
Problem with nist_ri() function

### ISSUE THREAD

**Issue by Facke-ito** [ropensci/webchem#176]
Dear All,

I faced a problem with nist_ri() function today

When I called nist_ri("75.2.123") I got the following answer:

Error in map (cas, ~get_ri_xml(., type, polarity, temp_prog)) %>% setNames (cas) : impossible to find the function "%>%"

**Comment by Facke-ito** [comment]
I remove %>% from the nist_ri() function and I get this answer : 

Error in setNames(cas) : 
  "nm" argument is missing, without any default value

**Comment by Aariq** [comment]
"75.2.123" isn't a valid CAS number.  Regardless, this isn't the error you should get when that's the case.  Can you check if you have `dplyr` installed?  The pipe (`%>%`) is from `dplyr`, which is supposed to be imported by `nist_ri`.

**Comment by Facke-ito** [comment]
Yes, but actually installation from Github failed on my PC. I finally managed to get information selecting function from the zip file! You were right I forgot to launch some librairies. 

Any ideas for the absence of nist_ri() function in the CRAN version of webchem?

Because it is definitely a super work, thanks for all developers!

**Comment by Aariq** [comment]
It was added more recently than the most recent CRAN version.  I think we need to fix all the broken chemspider functions (they updated their API) before the next version.  I'm very glad to hear the package has been helpful to you!

**Comment by Facke-ito** [comment]
Ok, I'll do a watch on it!

**Comment by Aariq** [comment]
This is resolved and can be closed @stitam

**Comment by stitam** [comment]
Thank you for opening this issue @Facke-ito, if you encounter any other problems, let us know!
