### ISSUE TITLE
Get an RRID for webchem

### ISSUE THREAD

**Issue by Aariq** [ropensci/webchem#177]
https://scicrunch.org/resources

rOpenSci appears to have a RRID, but not specifically `webchem`, as far as I can tell.

**Comment by stitam** [comment]
I didn't know about the Resource Identification Initiative, thanks. I see that R, CRAN, and ggplot2 are also registered as `Tools`, I agree it would be great to register webchem as well.

**Comment by stitam** [comment]
I have added webchem as a new resource, RRID will be SCR_017684 but it is not live yet. Is RRID the preferred way for citing software? What I mean is should we update the citation? If yes, I will open a PR for this.

**Comment by Aariq** [comment]
I think the current citation is probably better since it has a DOI associated with it, and people are more familiar with DOI than with RRID.  Eventually, the best citation would be a peer-reviewed publication.

**Comment by stitam** [comment]
Our RRID is live! 
https://scicrunch.org/resources/Any/search?q=webchem&l=webchem
RRID:SCR_017684

I agree with people being more familiar with DOI than RRID.
Anyway, should anyone need our RRID, we have one:)
I am closing the issue.
