### ISSUE TITLE
PAN Database API fails

### ISSUE THREAD

**Issue by currmi01** [ropensci/webchem#181]
-> pan_query() function in the webchem package does not work.

The API to the PAN database does not work with the latest PAN database from 2019 (I did not check it with older databases). Using the example provided in the documentation file:

```r
library("webchem")
pan_query("Triclosan")
#> http://www.pesticideinfo.org/List_Chemicals.jsp?ChemName=Triclosan
#> Error in strsplit(out[["Chemical Name and matching synonym"]], "\\n"): non-character argument
```

**Comment by jmorim** [comment]
See #168, this issue is present in the CRAN version but not development
