### ISSUE TITLE
Amount of data accessible with this pkg?

### ISSUE THREAD

**Issue by sckott** [ropensci/webchem#184]
👋  as part of preparing an rOpenSci annual report, we're trying to estimate amount of data the various pkgs in our suite provide access to.

Do you have a sense for how much data (e.g., in GB) one can access through this pkg?  And whatever metric is most relevant for this data?

**Comment by Aariq** [comment]
Probably the easiest number to obtain is the number of entries in each database.  For example, right on the front page of chemspider it says they have data for 67 million structures.  There's going to be some overlap in the data available from different databases, but that's probably a good starting metric that's easy to get.

**Comment by sckott** [comment]
thanks @Aariq ! Also got some details from @eriksapper in Slack. I think i'm all set, thanks very much

**Comment by Aariq** [comment]
Chemspider: 67 million structures
Pubchem: 236 million substances
PAN pesticides: ???
Alan Wood's Compendium: 1800 active ingredients
PHYSPROP: 41,000 chemicals
ETOX: 64,500 entries
PPDB: ???
ChemIDplus: ???
WikiData: ???
Flavornet: 738 odorants
NIST: 40,000 entries

**Comment by EDiLD** [comment]
Cool, this could also go into the paper...

Eduard
Dr. Eduard Szöcs
eduardszoecs@gmail.com (https://link.getmailspring.com/link/D8866F57-601D-4243-9806-2F33F6F78ED9@getmailspring.com/0?redirect=mailto%3Aeduardszoecs%40gmail.com&recipient=cmVwbHkrQUFHUE5VR1paWEMzSEM3NkFSVVJFSkYzVUlMRjNFVkJOSEhCM1hDU1hRQHJlcGx5LmdpdGh1Yi5jb20%3D)

**Comment by stitam** [comment]
I have added them to the paper.
