### ISSUE TITLE
option in get_csid() to return named vector rather than list

### ISSUE THREAD

**Issue by Aariq** [ropensci/webchem#191]
Other cs_*() functions take vectors of IDs, so the current implementation of `get_csid()` doesn't play nice with them when looking for results for more than one compound.

```r
library(webchem)
apikey <- <secret>
(ids <- get_csid(c('Triclosan', "hexane"), apikey = apikey))
#> $Triclosan
#> [1] 5363
#> 
#> $hexane
#> [1] 7767
# cs_compinfo(ids, fields = c("Formula", "MolecularWeight"), apikey = apikey) #errors
cs_compinfo(c(5363, 7767), fields = c("Formula", "MolecularWeight"), apikey = apikey)
#>     id                formula molecularWeight
#> 1 5363 C_{12}H_{7}Cl_{3}O_{2}        289.5418
#> 2 7767            C_{6}H_{14}         86.1754
```

**Comment by Aariq** [comment]
Once fixed, the example in the README should get updated too.

**Comment by Aariq** [comment]
Oh, hmm.. I didn't realize compounds can have multiple csid's. Maybe an alternate solution is to have an optional `first = TRUE` argument that returns a vector with only one ID per query.

**Comment by stitam** [comment]
@Aariq do you agree that we can postone this issue for v0.6.0?

**Comment by Aariq** [comment]
I think that's fine.  We might want to fix the README though. Right now
there is code in the ChemSpider section that is commented out because it
was throwing errors.

**Comment by Aariq** [comment]
I'm closing this for now because the README is fixed and we haven't settled on a consistent output for `get_*` functions. (see #193)
