### ISSUE TITLE
Update cs_prop() to capture all information from EPI Suite

### ISSUE THREAD

**Issue by stitam** [ropensci/webchem#198]
This issue is related to issue #197. `cs_prop()` already gathers chemical information from EPI Suite by scraping the ChemSpider [website](https://www.chemspider.com/Default.aspx). However, not all the information seems to be gathered.

**Comment by stitam** [comment]
Also related to issue #132 and issue #135

**Comment by Aariq** [comment]
cs_prop() has now been deprecated because ChemSpider forbids scraping
