### ISSUE TITLE
get_etoxid() returns incorrect results for certain match types

### ISSUE THREAD

**Issue by stitam** [ropensci/webchem#201]
Match types available: `"best"`, `"all"`, `"first"`, `"ask"`, `"na"`.

Reproducible example, try: 
`data("jagst", package = "webchem")`
`subs <- head(unique(jagst$substance))`
`get_etoxid(subs, match = "best")`
`get_etoxid(subs, match = "all")`
`get_etoxid(subs, match = "first")`
`get_etoxid(subs, match = "ask")`
`get_etoxid(subs, match = "na")`

- [x] `"all"` returns an unformatted list
- [x] '"first"` seems shifted. doesn't print etoxid, match is na, distance is first
- [x] `"ask"` is not working
- [x] `"na"`should not return na for Desethylatrazin.

**Comment by Aariq** [comment]
Let’s switch this to use `chooser()` internally?
