### ISSUE TITLE
Convert chemcal formula to CID or compound name

### ISSUE THREAD

**Issue by MjelleLab** [ropensci/webchem#206]
Is it possible to convert chemical formula such as "C47H93N2O6P" to CID or compound name?

**Comment by Aariq** [comment]
Because there are many chemicals with that formula, I'm not sure that we have a function that does this.

**Comment by Aariq** [comment]
Actually, I take that back.  I think you *should* be able to use `get_csid("C47H93N2O6P")` to do this, but right now it seems to only return an empty list.  `get_csid("H2O")` works, for example, but returns IDs for compounds other than water.  Any ideas @stitam ?

**Comment by andschar** [comment]
I had a deeper look at the function and I realized that we are querying the name-endpoint of the API in `get_csid()`:
https://developer.rsc.org/compounds-v1/apis/post/filter/name
H2O seems to be a name too for Chemspider that's why a result is returned. However there's a specific formula-endpoint for that, which also returns a result for the OP's formula: C47H93N2O6P
https://developer.rsc.org/compounds-v1/apis/post/filter/formula
The best would probably be, to use an argument to specify which API endpoint to query, meaning `type = 'formula'` or similar.

**Comment by andschar** [comment]
I could work that in for `get_csid()` if you want. Also for the v0.5.0 release, since I can spare some time this week.

**Comment by biocoreexpert** [comment]
Hi, that would be great!

**Comment by stitam** [comment]
Thanks @biocoreexpert for raising this issue also @andschar for the detailed answer about `get_csid()`. True, the function currently implements the name endpoint, and implementing the formula endpoint would allow us to create csid from formula. Would this help? However, with the ChemSpider APIs we can only convert csid to inchi, inchikey, smiles or mol. I tried the csid -> name conversion with CTS but it doesn't seem to work (not even on the website).

In general, `get_cid()` (note: cid, not csid) accepts formulae. I tried it with H2O and C3H8NO5P (glyphosate) and it works, although for some reason it returns only one result whereas the website returns more, we'll look into this. However, for C47H93N2O6P it doesn't return anything, whereas the website returns 60 results. On the other hand, if I take the CID from the website, `pc_prop()` will return an object that contains the IUPAC name of the compound. Hope this helps @biocoreexpert, if you have more compounds, try `get_cid()`, it might work for some. Thanks again for bringing this up!

**Comment by stitam** [comment]
Hi @MjelleLab, a small update on this issue: to convert formula to name using ChemSpider, a good strategy would be formula -> csid -> name. `get_csid("C47H93N2O6P", from = "formula")$csid %>% cs_compinfo(fields = "CommonName)` now gives you the same results as the website search.

**Comment by stitam** [comment]
Hi @MjelleLab, we updated `get_cid()` and added a new function `pc_sect()`.

```
# This returns a tibble of 60 compounds, in the same order as the PubChem website query:
# https://pubchem.ncbi.nlm.nih.gov/#query=C47H93N2O6P
cids <- get_cid("C47H93N2O6P", from = "formula") 

# This returns a tibble of IUPAC names, as printed on a PubChem content page such as this:
# https://pubchem.ncbi.nlm.nih.gov/compound/134757636#section=3D-Status
# The IUPAC names are in the Result column.
# BTW, all `pc_sect()` queries return a compound name in the Name column.
names <- pc_sect(cids$cid, section = "iupac name")
```

Does this solve your issue?

**Comment by apuhegde** [comment]
Hi,
I get the following error when I try this command:

```
Service not available. Returning NA.
Error in get_cid("C26H52NO6P", from = "formula")
```
