### ISSUE TITLE
Returning incomplete CID list from PubChem given CAS

### ISSUE THREAD

**Issue by wdkrnls** [ropensci/webchem#214]
According to PubChem the dichlorobenzene mixture CAS 25321-22-6 should be assigned CID 10943. webchem is returning only CID 7239 even if `first=FALSE`.

```r
get_cid("25321-22-6", first = FALSE)
```

https://pubchem.ncbi.nlm.nih.gov/#query=25321-22-6
https://pubchem.ncbi.nlm.nih.gov/compound/m-dichlorobenzene
https://www.chemicalbook.com/CASEN_25321-22-6.htm

**Comment by andschar** [comment]
Your function call uses the `from = 'name'` default setting, meaning that you search in the PubChem names for the CIDs. You basically send the following url to PubChem, which only returns one CID (which is also only half correct - see wikipedia article below):

https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/25321-22-6/cids/JSON

Unfortunately, AFAIK their is no option in the API to search for CAS numbers, hence we we don't have an option such as `from = 'cas'`. I recommend you to search the CIDs by inchikeys or smiles identfiers. You could do:

```
todo = c('RFFLAFLAYFXFSW-UHFFFAOYSA-N',
         'ZPQOPVIELGIULI-UHFFFAOYSA-N',
         'OCJBOOLMMGQPQU-UHFFFAOYSA-N')
get_cid(todo, from = 'inchikey')
```
The german wikipdeia article on [25321-22-6](https://de.wikipedia.org/wiki/Dichlorbenzole) tells you that this is the ambiguous CAS for 1,2-Dichlorbenzol, 1,3-Dichlorbenzol and 1,4-Dichlorbenzol. So it's better to stick to inchikeys here anyway.

**Comment by wdkrnls** [comment]
I see. Thanks for the suggestion!
