### ISSUE TITLE
Getting retention index from name, InChIKey ?

### ISSUE THREAD

**Issue by Sukis123** [ropensci/webchem#219]
Dear webchem developer,
Thank you very much for your effort in developing and maintaining webchem. It is a very useful tool for many of us. 
I am thinking if it is possible to retrieve retention index information by name/nist number/InChIKey because I found that there are many compounds that do not have CAS number

**Comment by Aariq** [comment]
Thanks for the suggestion!  These should be pretty easy to implement.

**Comment by Aariq** [comment]
I spoke too soon.  You can query chemicals by name, CAS, or InChIKey, but the URL for the individual tables is by CAS number, so it's not actually easy to implement this.

Can you give an example of a compound with no CAS number that has gas chromatography data in NIST?  That would help me figure out if this is possible.

**Comment by Sukis123** [comment]
For example, Longipinene (HICYDYJTCDBHMZ-QVHKTLOISA-N), https://webbook.nist.gov/cgi/cbook.cgi?ID=R628941&Units=SI&Mask=2000#Gas-Chrom . Maybe it is not common.  Best regards,Qi-Zhi Su From: Eric R ScottSent: 2020年3月6日 23:27To: ropensci/webchemCc: Sukis123; AuthorSubject: Re: [ropensci/webchem] Getting retention index from name, InChIKey ? (#219) I spoke too soon. You can query chemicals by name, CAS, or InChIKey, but the URL for the individual tables is by CAS number, so it's not actually easy to implement this.Can you give an example of a compound with no CAS number that has gas chromatography data in NIST? That would help me figure out if this is possible.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Aariq** [comment]
Thanks.  It probably is possible to implement this, but not as straightforward as I thought.  The permanent link to compound pages is by InChI, and from there I could grab the URL for the gas chromatography data page.

**Comment by Sukis123** [comment]
By InChI could be a good option as well. Best regards,Qi-Zhi Su From: Eric R ScottSent: 2020年3月10日 23:42To: ropensci/webchemCc: Sukis123; AuthorSubject: Re: [ropensci/webchem] Getting retention index from name, InChIKey ? (#219) Thanks. It probably is possible to implement this, but not as straightforward as I thought. The permanent link to compound pages is by InChI, and from there I could grab the URL for the gas chromatography data page.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Aariq** [comment]
You can now use `nist_ri()` to search by cas, inchi, inchikey, and compound name in the development version of `webchem`.  Install the development version with `remotes::install_github("ropensci/webchem")`
