### ISSUE TITLE
Empty Etox tables

### ISSUE THREAD

**Issue by andschar** [ropensci/webchem#227]
The following call returns an error because the table doesn't contain any data: 
```r
etox_basic(99015)
```
https://webetox.uba.de/webETOX/public/basics/stoff.do?language=en&id=99015
The code breaks [here](https://github.com/ropensci/webchem/blob/dad1b7468afbc86a3ee830265c8fea92ed60893f/R/etox.R#L193).
Maybe we could add something like 
```r
if (inherits(tabs, 'try-error')) {
  message('ID not found! Returning NA.\n')
  return(data.frame(NA))
}
```
Not sure about it though.

**Comment by stitam** [comment]
I think this could work. However, this topic is related to issue #224, and PR #225. An invalid input to the etox functions should return a structure that allows subsequent vectorised extraction of elements, e.g. cas number in this case, so `return(data.frame(NA))` might not be sufficient.

**Comment by andschar** [comment]
Do we already know how many extractor functions we want to have? Currently there are cas, inchikey and smiles.

**Comment by stitam** [comment]
I think the more the better:) I am currently working on some extractors for alanwood and chebi (only cas, inchikey, smiles)
