### ISSUE TITLE
fail in nist_ri 

### ISSUE THREAD

**Issue by Ahmedserag777** [ropensci/webchem#236]
Hello Wbchem developer, Thank you for your contributions in the field.
I am trying to retrieve the RI data using nist_ri function for a huge  number of compounds but  I got this error message and my loop stopped
 "Error in open.connection(x, "rb") :
schannel: next InitializeSecurityContext failed: SEC_E_MESSAGE_ALTERED (0x8009030F) - The message or signature supplied for verification has been altered"
I have NIST08 which I used to retrieve the case number of more than 20000 compound then I am trying to retrieve their retention indices via webchem.
Is there any way to tackle this error and continuing my loop ? 
An important note is that this error message appear if I tried to retrieve more than 100 compound only.

Thanks

**Comment by stitam** [comment]
Thank you @Ahmedserag777 for raising this issue. @Aariq do you think PR #232 will solve this?

**Comment by Aariq** [comment]
Does `nist_ri()` work with small numbers of compounds?  E.g.

```
out <- nist_ri(
      c("78-70-6", "13474-59-4"),
      type = "linear",
      polarity = "non-polar",
      temp_prog = "ramp"
)
```

What operating system are you on?  This could be related to an error in `crul` on Windows 7 (https://github.com/jeroen/curl/issues/127)

**Comment by Aariq** [comment]
@Ahmedserag777  We've just pushed an update to the package.  Can you try installing the development version and see if you still get this error?

**Comment by Ahmedserag777** [comment]
> Does `nist_ri()` work with small numbers of compounds? E.g.
> 
> ```
> out <- nist_ri(
>       c("78-70-6", "13474-59-4"),
>       type = "linear",
>       polarity = "non-polar",
>       temp_prog = "ramp"
> )
> ```
> 
> What operating system are you on? This could be related to an error in `curl` on Windows 7 ([jeroen/curl#127](https://github.com/jeroen/curl/issues/127)). `curl` is used by `xml2`, which is used by `nist_ri`. This might be fixed in the upcoming version with PR #232, but I'm not sure.

Thank you  @Aariq. This error occurs only while retrieving large number  of compounds

**Comment by Ahmedserag777** [comment]
> @Ahmedserag777 We've just pushed an update to the package. Can you try installing the development version and see if you still get this error?

Thank you @Aariq for your efforts. I will try it and give you my feedback.

**Comment by Aariq** [comment]
I'm going to go ahead and close this for now, as I wasn't able to reproduce it, and I think it is fixed.
