### ISSUE TITLE
Simplify README

### ISSUE THREAD

**Issue by Aariq** [ropensci/webchem#254]
Our README is getting a little out of hand IMO.  I think much or all of the code could be removed (or moved to a vignette?) and the table of services could be turned into a bulleted list.  Should have title, description, how to install, contribution statement and maybe one or two examples of functionality.  Maybe one chemical translation example and one example of retrieving properties.

**Comment by stitam** [comment]
I agree. An alternative to vignette could be a GitHub wiki page for each data source?

**Comment by stitam** [comment]
Maybe instead we could add to README articles we know of that cited webchem?

**Comment by Aariq** [comment]
> I agree. An alternative to vignette could be a GitHub wiki page for each data source?

Or a `pkgdown` website

**Comment by andschar** [comment]
I agree. Should we maybe split the README in sections. Maybe like this:

- `get_*()` functions
  - in a table or bullet points
  - to resolve and get IDs
- `*_query()` and other functions
  - to retrieve data
  - only a few examples here
- `*_img()` functions

Not sure, whether to choose `pkgdown` or GitHub wiki. The `pkgdown` website would then be hosted on [ropensci.github.io/webchem](url) ?

**Comment by stitam** [comment]
@andschar do you mean you would list _all_ `get_*()` functions in README, etc.? I was wondering if it would be enough to show only a few examples instea, and create a separate tutorial page for each web service. Some of them can be quite complex, I think it would be best if each had their own pkgdown/wiki page so we can show all the functionality.

So far I don't see the pros and cons of `pkgdown` vs GitHub pages. Are rOpenSci docs created by `pkgdown`? https://docs.ropensci.org/webchem/

**Comment by andschar** [comment]
@sitam yeah, you are right. It's better to not include all `get_*()` functions in the README

**Comment by Aariq** [comment]
> Are rOpenSci docs created by pkgdown? https://docs.ropensci.org/webchem/

Yes I think so.  Check out the page for `skimr`.  They've got "get started", "reference", "articles" and "Changelog" in their nav bar: https://docs.ropensci.org/skimr/index.html

**Comment by Aariq** [comment]
the answer from Scott on Slack: 
>yes, pkgdown. you can use a pkgdown config file just as you would if you built it locally or on github pages
10:42
its essentially like github pages or netlify - but its our own server with Jenkins orchestrating

**Comment by stitam** [comment]
So the outcome will be an rOpenSci docs page which is better structured, right? If yes, then i think `pkgdown` is absolutely the way to go. And we should all learn it:)
