### ISSUE TITLE
pan_query() coercing NAs

### ISSUE THREAD

**Issue by Aariq** [ropensci/webchem#258]
`pan_query()` currently expects certain outputs to be numeric and converts them to numeric with `as.numeric()`, but in at least one situation, there is extra information as text, so `as.numeric()` coerces it to an `NA`

The "livestock water guideline" for Chlorpyrifos is "24 (interim)" on the [web](http://www.pesticideinfo.org/List_Chemicals.jsp?ChooseSearchType=Begin&ResultCnt=50&dCAS_No=y&dEPA_PCCode=y&dDPR_Chem_Code=y&dUseList=y&dClassList=y&dMol_weight=y&dEPA_Reg=y&dCA_Reg=y&dPIC=y&dPOP=y&dWHOObsolete=y&dEPA_HAP=y&dCA_TAC=y&dS_GrdWat=y&dDPR_GrdWatCont=y&dS_AquaAcute=y&dS_AquaChronic=y&dS_BA=y&dDirtyDozen=y&dS_Acute=y&dS_ChEInhib=y&dEPAAcute=y&dNTPAcute=y&dPANAcute=y&dTRI_Acute=y&dWHOAcute=y&dS_Cancer=y&dEPACancer=y&dIARCCancer=y&dNIHCancer=y&dp65_Cancer=y&dTRI_Cancer=y&dS_DevRep=y&dp65_Dev=y&dTRI_Dev=y&dp65_Female=y&dp65_Male=y&dTRI_Repr=y&dS_ED=y&dED_EU=y&dED_Benbrook=y&dED_Denmark_Inert=y&dED_Colborn=y&dED_Illinois_EPA=y&dED_Keith=y&dAvg_Sol=y&dAvg_Koc=y&dAvg_Hydrolysis=y&dAvg_Aerobic=y&dAvg_Anaerobic=y&dMCL=y&dMCLG=y&dOneDay=y&dTenDay=y&dLifetime=y&dRfD=y&dDWEL=y&dCancerRisk=y&dMAC=y&dIMAC=y&dAO=y&dFWCont=y&dFWMax=y&dSWCont=y&dSWMax=y&dHumConsOrgOnly=y&dHumConsWaterOrg=y&dEPAOrganoleptic=y&dCanAquaFWConc=y&dCanAquaMarineConc=y&dIrrigConc=y&dLivestockConc=y&ChemName=chlorpyrifos), so currently `pan_query()` returns `NA`

We could 1) replace `as.numeric` with `extr_num` and the output would be `24`or  2) change it to not expect this (or any??) column to be numeric and return `"24 (interim)"`.

## Minimal reproducible example
library(webchem)
x <- pan_query("chlorpyrifos")
#> http://www.pesticideinfo.org/List_Chemicals.jsp?ChemName=chlorpyrifos
#> Warning in lapply(out[tonum], as.numeric): NAs introduced by coercion
x$chlorpyrifos$`Livestock Water Guidelines (ï¿½g/L)`
#> [1] NA

**Comment by stitam** [comment]
I think the purpose of the package is to return data from the web service not to process it, so I think best would be to leave it as character. I'll add it to my next PR.

**Comment by stitam** [comment]
Fixed in PR #260.
