### ISSUE TITLE
standardize "from"

### ISSUE THREAD

**Issue by Aariq** [ropensci/webchem#262]
In all of the `get_()` functions, the argument to specify what type of identifier the query is is called `from`, but in a couple of functions, this argument is `type`.

- `ci_query(query, type = "inchikey")`
- `aw_query(query, type = "cas")`

A couple of functions don't have `query` and `from` because they only accept one identifier type in queries.  Maybe these are OK as is?

- `fn_percept(CAS)`
- `cts_compinfo(inchikey)`

In addition, the possible values that `from` accepts are mostly standardized, except for:

- `aw_query`, which uses `"commonname"` instead of `"name"`
- `get_chebiid()` which is more complicated:

>character; type of input, can be one of 'ALL', 'CHEBI ID', 'CHEBI NAME', 'DEFINITION', 'ALL NAMES', 'IUPAC NAME', 'CITATIONS', 'REGISTRY NUMBERS', 'MANUAL XREFS', 'AUTOMATIC XREFS', 'FORMULA', 'MASS', 'MONOISOTOPIC MASS', 'CHARGE', 'INCHI/INCHI KEY', 'SMILES', 'SPECIES'.

It might be nice if this wasn't case-sensitive and if both "inchi" and "inchikey" were options rather than "INCHI/INCHI KEY" and maybe if "name" was a synonym for "ALL NAMES" to better standardize across the package.

**Comment by Aariq** [comment]
`cts_convert()` is also case-sensitive and it would be nice if it wasn't.

**Comment by Aariq** [comment]
One advantage of standardizing all this stuff is the possibility of something like an "autotranslate" feature:

```
get_auto <- function(query, from, .f, ...) {
  f <- rlang::as_function(.f)
  pos_froms <- eval(rlang::fn_fmls(f)$from)
  if (from %in% pos_froms) {
    f(query, from, ...)
  } else {
    new_from <- pos_froms[pos_froms != "name"][1] #cts name conversion broken
    warning(glue::glue("{.f} doesn't accept {from}. Attempting to translate to {new_from} with CTS and re-running query "))
    new_query <- cts_convert(query, from = from, to = new_from, choices = 1)
    f(new_query, new_from, ...)
  }
}

get_auto('1071-83-6', "cas", "get_etoxid")
get_auto('XDDAORKBJWWYJS-UHFFFAOYSA-N', "inchikey", "get_etoxid")
```

Not sure how important this is for the average user, but might be useful in the future for functions that integrate across databases.

**Comment by stitam** [comment]
Thanks @Aariq, I think it would be great to standardise available `from` arguments across the package and to consistently use `from` (and not `type`) everywhere. Probably simpler for all users and also for us to build integrators later on. Same for the functionality you described above. Maybe I would call `get_id()` the one that returns database specific ids like csid or cid, and `convert_id()` the one that converts between universal identifiers like cas or inchi.

**Comment by Aariq** [comment]
Yeah, I don't know the final form of this function.  It could work kinda like `purrr::safely()`, where it returns a modified function (one that auto-translates ID's).  Or it could be `get_id(query, from, database)`.  Or maybe it's something we only use internally for figuring out database coverage for compounds.  But it sounds like you're ok with standardizing `from` wherever it makes sense, so I'll work on that as a start.
