### ISSUE TITLE
'matcher()` and `match = ` should supersede `chooser()` and `choices = `?

### ISSUE THREAD

**Issue by Aariq** [ropensci/webchem#263]
I propose deprecating `choices = ` for all the functions that use it in favor of `match = `.  I know I created `choices = ` and pushed for it, but I think I like the behavior of `match = ` better now, and it would bring some consistency to the package.
I feel a little bad for the confusion this would introduce (deprecating `first` in favor of `choices`, now deprecating `choices` in favor of `match`), but it seems worth it maybe.

**Comment by Aariq** [comment]
affected functions would include:

- `cts_convert()`
- `pc_synonyms()`
- `cir_query()`

In addition, `get_etoxid()` uses the `chooser()` function internally, although it has a `match` argument.  It should probably be switched to use the `matcher()` utility function and then we can completely get rid of the `chooser()` utility.

**Comment by stitam** [comment]
That functionality was kind of evolving over time. I think it's fine that we experimented with it and I agree that `match` is probably the best approach we currently have. If you want to make this more consistent, feel free to go ahead, and thanks!

**Comment by Aariq** [comment]
I think I got all the instances of this.  `chooser()` is still in utils.R though, so I'll leave this open until we remove it?
