### ISSUE TITLE
removal of cs_smiles_inchi and cs_inchikey_inchi

### ISSUE THREAD

**Issue by korseby** [ropensci/webchem#275]
Hi,

it seems that the function `cs_smiles_inchi` has been removed in favour of `cs_smiles_csid`...

A similar thing occured with `cs_inchikey_inchi`...

I could not find any documentation of that. How can I get the same results as with `cs_smiles_inchi` / `cs_inchikey_inchi` with the latest version of webchem?

```r
# Minimal example:
smile <- 'CC(C(O[C@H]([C@@H](OC(C(C)C)=O)[C@@H](OC(C(C)C)=O)O[C@@H]1CO)[C@@H]1O)=O)C'
webchem::cs_smiles_inchi(  smiles = smile,      verbose = FALSE)
```

**Comment by stitam** [comment]
Thank you @korseby for raising this issue and sorry about removing these functions without deprecating them first.

The alternative is now the `cs_convert()` function:

```
cs_convert("CC(C(O[C@H]([C@@H](OC(C(C)C)=O)[C@@H](OC(C(C)C)=O)O[C@@H]1CO)[C@@H]1O)=O)C", from = "smiles", to = "inchi", apikey = apikey)
[1] "InChI=1/C18H30O9/c1-8(2)15(21)25-13-12(20)11(7-19)24-18(27-17(23)10(5)6)14(13)26-16(22)9(3)4/h8-14,18-20H,7H2,1-6H3/t11-,12-,13+,14-,18-/m1/s1"
```

The function can convert between multiple identifiers, but not all conversions are supported through the new APIs. The list of supported conversions can be found in the function documentation. Does this answer your question?

**Comment by korseby** [comment]
Thanks. It just would have been great to find some documentation on this. Anyway. This fixes the issue. :)
