### ISSUE TITLE
plot from find_db() crops compound names

### ISSUE THREAD

**Issue by Aariq** [ropensci/webchem#277]
Someone better versed in base R plotting might be able to figure out how to get the plot margins to adjust according to the size of the axis tick labels.  I couldn't figure it out, so long compound names are cropped.

```r
library(webchem)
data("jagst")
subs <- unique(jagst$substance)
find_db(subs[1:3], from = "name", sources = c("etox", "pan", "srs"), plot = TRUE)
```
![image](https://user-images.githubusercontent.com/25404783/90684443-33007200-e236-11ea-8714-182cca0c19bb.png)

**Comment by stitam** [comment]
What do you think of this?

```
leftmargin <- 0.5*max(nchar(query))
graphics::par(mar = c(5.1, leftmargin, 4.1, 4.1))
```
