### ISSUE TITLE
get_cid fails with search via SMILES in Pubchem

### ISSUE THREAD

**Issue by stephanflemming** [ropensci/webchem#283]
Some of my queries for SMILES in Pubchem result in NA, while the Pubchem search is able to find that compound.

Example: O=S(=O)(NCCNC/C=C/c1ccc(Br)cc1)c2cccc3cnccc23

https://pubchem.ncbi.nlm.nih.gov/compound/449241

and 

```
> get_cid("O=S(=O)(NCCNC/C=C/c1ccc(Br)cc1)c2cccc3cnccc23", from = "smiles")
Querying O=S(=O)(NCCNC/C=C/c1ccc(Br)cc1)c2cccc3cnccc23. Bad Request (HTTP 400).
# A tibble: 1 x 2
  query                                         cid  
  <chr>                                         <lgl>
1 O=S(=O)(NCCNC/C=C/c1ccc(Br)cc1)c2cccc3cnccc23 NA  
```

I am using the development version 1.0.0.9000.

Thanks in advance!

**Comment by stitam** [comment]
Hi @stephanflemming thanks for raising this issue.

When I search for "O=S(=O)(NCCNC/C=C/c1ccc(Br)cc1)c2cccc3cnccc23" on PubChem (so not through webchem), it finds CID 449241, but according to the PubChem page of CID 449241, the smiles of the compound is "C1=CC2=C(C=CN=C2)C(=C1)S(=O)(=O)NCCNCC=CC3=CC=C(C=C3)Br". I am unsure why the two smiles IDs don't match. When I search for "C1=CC2=C(C=CN=C2)C(=C1)S(=O)(=O)NCCNCC=CC3=CC=C(C=C3)Br" I get CID 3541, and I don't get CID 449241. However the two compounds, CID 449241 and CID 3541 appear to be the same. This is strange, I am unsure what's happening.

Regardless, our understanding has been that `get_cid()` returns the exact same output as the search bar on PubChem. Based on your finding, either the search bar is more sophisticated that that or `get_cid()` does something wrong. We'll work on it.

If you could provide more examples, that would be great.

**Comment by Aariq** [comment]
If you look closely at the web API search results, it says "Find structures very closely related to the input, comparing chemical connectivity, and optionally tautomers, stereoisomers, and isotopes."  So I think the web search is doing something slightly different and returning compounds that are very close matches to the query.

**Comment by schymane** [comment]
So, we ran into this the last couple of days and thanks to Paul Thiessen from PubChem we have a diagnostics and hopefully a solution!

So - the problem: 
```
library(webchem)
csv_url <- "https://gitlab.lcsb.uni.lu/emma.schymanski/debugging/-/raw/main/CORE_PFAS_PubChem_debugging.csv"
cmpd_data <- read.csv(csv_url,stringsAsFactors = F)

smiles1 <- cmpd_data$SMILES[1] #works
smiles2 <- cmpd_data$SMILES[4] #fails
smiles3 <- cmpd_data$SMILES[5] #fails
smiles4 <- cmpd_data$SMILES[7] #fails 

get_cid(smiles1,from="smiles",domain="compound")
# 3763
get_cid(smiles2,from="smiles",domain="compound")
# NA
get_cid(smiles3,from="smiles",domain="compound")
# NA
get_cid(smiles4,from="smiles",domain="compound")
# NA
```
If you build the URL as currently done in webchem:

```
domain <- "compound"
from <- "smiles"
query <- smiles1
qurl1 <- paste("https://pubchem.ncbi.nlm.nih.gov/rest/pug",
               domain,
               from,
               URLencode(as.character(query), reserved = TRUE),
               "cids",
               "json",
               sep = "/")
qurl1
# paste into browser, CID 3763 is returned

query <- smiles2
qurl2 <- paste("https://pubchem.ncbi.nlm.nih.gov/rest/pug",
               domain,
               from,
               URLencode(as.character(query), reserved = TRUE),
               "cids",
               "json",
               sep = "/")
qurl2
# paste into browser: "PUGREST.BadRequest"

query <- smiles3
qurl3 <- paste("https://pubchem.ncbi.nlm.nih.gov/rest/pug",
               domain,
               from,
               URLencode(as.character(query), reserved = TRUE),
               "cids",
               "json",
               sep = "/")
qurl3
# paste into browser: "PUGREST.BadRequest"

query <- smiles4
qurl4 <- paste("https://pubchem.ncbi.nlm.nih.gov/rest/pug",
               domain,
               from,
               URLencode(as.character(query), reserved = TRUE),
               "cids",
               "json",
               sep = "/")
qurl4
# paste into browser: "PUGREST.BadRequest"
```

So, the construction of the URL is problematic for any SMILES with `"/"` in it, and will never work if the SMILES is in the middle of the URL, even if encoded. 

This is the URL format that will work: `/rest/pug/compound/smiles/cids/json?smiles=…`

```
query <- smiles1
fix_url1 <- paste0("https://pubchem.ncbi.nlm.nih.gov/rest/pug/",
                   domain, "/", 
                   from, "/", 
                   "cids/JSON?smiles=",
                   URLencode(as.character(query), reserved = TRUE))
fix_url1
# 3763

query <- smiles2
fix_url2 <- paste0("https://pubchem.ncbi.nlm.nih.gov/rest/pug/",
                   domain, "/", 
                   from, "/", 
                   "cids/JSON?smiles=",
                   URLencode(as.character(query), reserved = TRUE))
fix_url2
# 6442842

query <- smiles3
fix_url3 <- paste0("https://pubchem.ncbi.nlm.nih.gov/rest/pug/",
                   domain, "/", 
                   from, "/", 
                   "cids/JSON?smiles=",
                   URLencode(as.character(query), reserved = TRUE))
fix_url3
# 91699

query <- smiles4
fix_url4 <- paste0("https://pubchem.ncbi.nlm.nih.gov/rest/pug/",
                   domain, "/", 
                   from, "/", 
                   "cids/JSON?smiles=",
                   URLencode(as.character(query), reserved = TRUE))
fix_url4
# 136176
```

**Comment by Aariq** [comment]
Thank you for tracking this down so thoroughly!

**Comment by stitam** [comment]
Thanks again @stephanflemming for raising this issue and @schymane for tracking down the problem and suggesting the solution! I've implemented the fix.
