### ISSUE TITLE
rOpenSci webpage not updating

### ISSUE THREAD

**Issue by stitam** [ropensci/webchem#284]
Our rOpenSci webpage hasn't updated in a while. https://docs.ropensci.org/webchem/

**Comment by Aariq** [comment]
This is something rOpenSci does.  I don't know if there is a way we can force a new build.  Worth asking in the slack channel though.

**Comment by Aariq** [comment]
I'll post an issue at the [ropensci/docs](https://github.com/ropensci/docs) repo

**Comment by Aariq** [comment]
It doesn't build locally either on the master branch.  I tried building it with #271 though, and it builds.  It was getting stuck on running the examples in opsin_query(), but doesn't have that issue on the PR.

**Comment by stitam** [comment]
Fixed in PR #286. Thanks @Aariq.
