### ISSUE TITLE
`get_cid()` doesn't return query strings in returned data.frame when erroneous strings are queried

### ISSUE THREAD

**Issue by andschar** [ropensci/webchem#285]
The first query doesn't return query strings in the returned data.frame whereas the second does because of erroneous inputs.
```r
get_cid(c('Triclosan', 'miau', '', NA),
        from = 'name')

get_cid(c('Triclosan', 'Glyphosate'),
        from = 'name')
```
This happens because of `enframe()` and a missing name string (NA). Not sure what to think about `enframe()`.. If we were to return a `data.frame(query = query, cid = NA)` instead of `return(NA)` we wouldn't have this problem and wouldn't need something like `enframe()`. `dplyr::bind_rows` would suffice then. 

Not really related to #283

**Comment by stitam** [comment]
Thanks @andschar for raising this issue. I'd prefer `data.frame(query = query, cid = NA)`
