### ISSUE TITLE
Function to mangae wait times

### ISSUE THREAD

**Issue by andschar** [ropensci/webchem#287]
As discussed, a suggestion for a function to handle wait times for webchem requests. Please comment on it. Please also add comments on the policies of different web services and general recommendations, though I think this is very server specific. I will update the table.

```r
webchem_sleep <- function(time = NULL,
                          type = c('API', 'scrape')) {
  type <- match.arg(type)
  if (is.null(time)) {
    if (type == 'API') {
      time <- 0.2
    }
    if (type == 'scrape') {
      time <- 0.4
    }
  } else {
    if (!is.numeric(time)) {
      stop('Set time is not numeric.')
    }
  }

  Sys.sleep(time)
}
```

Recommended wait times for different web services:

| web service | time (s) | source | note |
|-----------------------|-------------------|----------|---------|
| ChEBI | x | https://www.ebi.ac.uk/chebi/webServices.do |
| Chemspider | x | https://developer.rsc.org/docs/compounds-v1-trial/1/overview | 1000 requests/month |
| CIR  | ? |  ? |
| Flavornet | x | | currently down |
| NIST | x | | |
| OPSIN | x | ? | | 
| PAN | x | | |
| Pubchem | 0.2 | https://pubchemdocs.ncbi.nlm.nih.gov/pug-rest |
| SRS | x | https://cdxnodengn.epa.gov/cdx-srs-rest/v2/api-docs | |
| Wikidata | x | https://www.wikidata.org/robots.txt | |

x...nothing stated
?...nothing found

**Comment by Aariq** [comment]
SRS has nothing listed in API docs
OPSIN has nothing listed in robots.txt

**Comment by Aariq** [comment]
PAN has nothing in docs or on robots.txt
Flavornet is down, but very unlikely that anything rate limits are documented as this is a small resource.
Nothing for NIST as far as I can find

**Comment by andschar** [comment]
So I think we go for 0.2 seconds wait default, since we haven't found any other value. Ok?
