### ISSUE TITLE
add citation to nist_ri()

### ISSUE THREAD

**Issue by Aariq** [ropensci/webchem#290]
Add the proper citation for the NIST retention index database to documentation for `nist_ri()`
Guide to constructing correct citation:

https://webbook.nist.gov/cgi/cbook.cgi?Contrib=

**Comment by jvfe** [comment]
Hi! I've used webchem in the past and wanted to contribute. I've read the contribution guide, could I work on this?

Just to be sure, this issue is to add this:

```
#' @references NIST Mass Spectrometry Data Center, William E. Wallace, director, "Retention Indices" in NIST Chemistry 
#' WebBook, NIST Standard Reference Database Number 69, Eds. P.J. Linstrom and W.G. Mallard, National Institute of 
#' Standards and Technology, Gaithersburg MD, 20899, https://doi.org/10.18434/T4D303.
``` 

to [nist.R#L307](https://github.com/ropensci/webchem/blob/1f67d44e2ed4b34677bff02e146bf453dc36deed/R/nist.R#L307)?

**Comment by Aariq** [comment]
Yeah, that looks right to me!  Feel free to add any other missing citations to the documentation if you find them.
