### ISSUE TITLE
xml2 ?

### ISSUE THREAD

**Issue by EDiLD** [ropensci/webchem#30]
Switch to xml2 package?

**Comment by EDiLD** [comment]
Currently I see not need for this

**Comment by sckott** [comment]
right, not a huge benefit perhaps, but if you don't need to create XML, then i'd go with `xml2` since it's likely to be supported going forward. Duncan's pkgs tend to be neglected it seems

**Comment by EDiLD** [comment]
Started to work with `httr` and `xml2` in the new `cs_*()` functions. Maybe change also others...

**Comment by EDiLD** [comment]
- [x] `allanwood.R`

**Comment by EDiLD** [comment]
Closed.
