### ISSUE TITLE
Have attach message only in interactive sessions?

### ISSUE THREAD

**Issue by maelle** [ropensci/webchem#305]
see e.g. https://github.com/tidyverse/ggplot2/blob/d6d847956f52aa7732c4cf78c9dae248ce8bf41c/R/zzz.r#L3 (where the message is also random, but I am guessing you don't really want that at the moment)

**Comment by stitam** [comment]
Thanks @maelle, great idea!

**Comment by stitam** [comment]
The attach message was no longer relevant and so it was removed in PR #311.
