### ISSUE TITLE
Get CAS from Pubchem?

### ISSUE THREAD

**Issue by Sukis123** [ropensci/webchem#308]
Dear developer, 

I am thinking if it is possible to retrieve CAS from Pubchem using cid ? It would be very nice to have such function. 

thanks in advance. 

Sukis

**Comment by stitam** [comment]
Hi @Sukis123, yes, it is possible, the function you need is `pc_sect()`. That functions can return most of the PubChem content pages, in your case, e.g. `pc_sect(6115, "cas")` will return a tibble of CAS registry numbers for aniline. In the future, this function may be renamed to something more helpful, e.g. `pc_section()".

**Comment by Sukis123** [comment]
Excellent! Thanks a lot.
