### ISSUE TITLE
ping_service() to use verbose and webchem_message()

### ISSUE THREAD

**Issue by stitam** [ropensci/webchem#309]
@Aariq recommended in PR #302 that `ping_service()` could have a verbose argument that would just call `webchem_message("service_down")` if the service is down.

**Comment by Aariq** [comment]
I think it's fine the way it is with the `if (!ping_service("service")) stop(webchem_message("service_down"))` pattern.  We want the "service_down" to be an error message in functions that query APIs, but we don't want `ping_service()` to error.
