### ISSUE TITLE
ci_query querying certain CAS rn returns information from another CAS rn

### ISSUE THREAD

**Issue by b8e5n** [ropensci/webchem#315]
When I query certain CAS, it is actually returning me the information from another CAS rn. The terminal actually shows a double query in these cases (see example). Then, the returned list contains the rightful CAS rn, but the content is what was retrieved from that successive query. The CAS in the second query is described as a "Related Registry Number", because it points to a salt form of the molecule (mono-hydrochloride salt, anhydrous).
Getting the information of a parent or a "child" would be interesting, but in this case, this is not was I am looking for.

```r
# test = ci_query("144-80-9",  from="rn", match="first")
```

Then, it queries the given CAS number, but it continues and queries a second one, here is the terminal output (without the data):
`Querying 144-80-9. OK (HTTP 200).`
`More then one Link found.  Multiple found. Returning first.`
`Querying 127-56-0. OK (HTTP 200).`

As mentioned earlier, the information in the test object is what you would get from querying the cas number "127-56-0".
$ 144-80-9
`$name`
`[1] "Acetamide, N-sulfanilyl-, N-sodium deriv"`
...
`$source_url`
`[1] "https://chem.nlm.nih.gov/chemidplus/rn/127-56-0"`

Since these two CAS are considered the same for whatever reasons, I tried to take the best, but results are the same as it is taking the first anyway. Unfortunately, there is no option to take exact match nor all matches. The only option would be to choose with ask, which I cannot use in an automated system.
`Warning message:`
`In matcher(hit_cas, query = URLdecode(query), result = hit_names,  :`
`  match = 'best' only makes sense for chemical name queries.`
` Setting match = 'first'."`

I think in such case, the "best" option would fit for an exact match of the query, and that it should be the default query.

-----------------------
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)
Matrix products: default
[1] webchem_1.1.0

**Comment by stitam** [comment]
Thanks @b8e5n for raising this issue, I managed to reproduce the output, this is definitely a bug.

**Comment by schymane** [comment]
There is a new CAS API out as of today apparently ... a subset of approx 500K 
https://commonchemistry.cas.org/api-overview 
Maybe of interest?
