### ISSUE TITLE
pc_sect fails, seemingly due to data frame colnames issue within pc_extract sub-function

### ISSUE THREAD

**Issue by pleeferguson** [ropensci/webchem#318]
Running `pc_sect` results in an error, regardless of the domain or section specified.  From my investigation, the problem seems to be related to column names in the `info` data frame created internally within the `pc_extract` sub-function called from `pc_sect`.  See example below.

---

```r
# From the pc_sect documentation example code:
> pc_sect(176, "pka")
Querying 176. OK (HTTP 200).
Error in `$<-.data.frame`(`*tmp*`, "SourceName", value = list()) : 
  replacement has 0 rows, data has 1
In addition: Warning message:
Unknown or uninitialised column: 'ReferenceNumber'. 
```

**Comment by pleeferguson** [comment]
Seems to be an issue with my local installation.

**Comment by stitam** [comment]
Hi @pleeferguson, thanks for opening the issue. I couldn't reproduce the error, so at this stage it seems the error is on your end. Have you found what's causing it?

**Comment by pleeferguson** [comment]
Hi, sorry yes I found that it was due to an old version of the `tibble` package, which apparently had some strange behavior with regard to column names when combining data sets.  I resolved it by upgrading the package.  Sorry opening this - I should have tested it on a different system beforehand.
