### ISSUE TITLE
Issue with is.cas function

### ISSUE THREAD

**Issue by tmoradkh** [ropensci/webchem#323]
I'm trying to use the is.cas function on dataframes containing CAS numbers. However when I run it I get the following error message:

Error in if (checksum%%10 != as.numeric(th)) { : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In FUN(X[[i]], ...) : NAs introduced by coercion

This function with other examples, though. Could it be an issue with the file I'm using?

**Comment by andschar** [comment]
Hi @tmoradkh ,
it's hard to judge from just the description whether something works or not. Please post some example code.

Here's an example that works:

```r
require(webchem)

vec = c('1071-83-6', '50-00-0', '456645645-35345-3453')
df = data.frame(vec)

is.cas(vec)
is.cas(df$vec)
```

**Comment by andschar** [comment]
Sorry, I won't open an external file. The best thing would be to paste a vector with the erroneous elements. You can use `dput()` to output a vector to your R console. Check [this guide on stackoverflow](https://stackoverflow.com/a/5963610/4742889) on how to create a reproducible example. Also note, that you can highlight code here on Github by using backticks.

**Comment by Aariq** [comment]
The fatal error comes from `is.cas(" 128-80-3")`.  I'm not entirely sure why, but the space before the cas number trips it up.  You can trim the whitespace with something like `str_trim()` from the `stringr` package and then it works.  E.g.

```
library(stringr)
is.cas(str_trim(CAS))
```

I'm not sure what your goal is, but I feel like I should point out that `is.cas()` is going to return FALSE for any CAS numbers without hyphens, and is definitely going to return FALSE for the entries that have multiple CASs separated by "/".  You might also check out `as.cas()` which will attempt to format CAS numbers correctly (if they are valid).

**Comment by Aariq** [comment]
This is a weird edge case.  Should probably return `FALSE`.  Alternatively, `is.cas()` could strip whitespace before checking validity?

**Comment by stitam** [comment]
Hi All, I think the bug is caused in line 250 of utils.R. in `di <- as.numeric(strsplit(gsub('^(.*)-(.*)-(.*)$', '\\1\\2', x), split = '')[[1]])`. If the input has a leading white space then `di` will have a leading `NA` and because of that that the checksum afterwards will be `NA` as well.

**Comment by tmoradkh** [comment]
OK. That would make sense, so I guess the same problem would also occur if a CAS number has a trailing white space.
