### ISSUE TITLE
How to translate fuzzy metabolite name into identifier id?

### ISSUE THREAD

**Issue by wanglu2014** [ropensci/webchem#324]
For a metabolite name , that we do not know which database it belong (such as tryptophan).  If it needed to be translate into identifier id (such as CHEBI), which function can do it?
Thank you for your help!

**Comment by wanglu2014** [comment]
@

**Comment by stitam** [comment]
Hi @wanglu2014 thanks for your question. Yes, to get for example the CHEBI ID of a compound you would use `get_chebiid()`. You can also use `get_csid()` to get ChemSpider IDs, or `get_cid()` to get PubChem IDs, etc. If you have more questions, let us know!
