### ISSUE TITLE
Why 'Bad Gateway (HTTP 502) happens'?

### ISSUE THREAD

**Issue by wanglu2014** [ropensci/webchem#325]
Retrieving data for taxon 'Abiotrophia defectiva'  error: Bad Gateway (HTTP 502)

data.frame(classification('Abiotrophia defectiva', db = 'itis',rows = 1)['Abiotrophia defectiva'],check.names = F)

**Comment by Aariq** [comment]
I don't think this is a function in the `webchem` package. Did you maybe mean to post this issue here: https://github.com/ropensci/taxize/issues ?
