### ISSUE TITLE
How to translate Human Metabolome database id into chebi id?

### ISSUE THREAD

**Issue by wanglu2014** [ropensci/webchem#326]
Could you kindly suggest how to translate Human Metabolome database id into chebi id?

**Comment by Aariq** [comment]
It looks like the [CTS web interface](https://cts.fiehnlab.ucdavis.edu/) takes Human Metabolome ID as an input, but it must not be implemented in their API yet, because I don't see it in the results of `webchem::cts_from()`.  My guess is you'll have to use the CTS web interface, for now at least.
