### ISSUE TITLE
get_csid() always returning error "Service not available. Returning NA." 

### ISSUE THREAD

**Issue by CesarIsguerra** [ropensci/webchem#368]
Hi. I'm having a permanent "Service not available. Returning NA." error result when using get_csid(). I was trying with a list of substances but found the issue remains even if I search for a single substance, as in:
```r
SustFaltantes_cs <- get_csid("3-Cyclohexene-1-methanol,.alpha.,.alpha.,4-trimethyl-, (S)-", apikey = 'Lt1Ah22zVgGvn2Lgn2UzH8zSAlnB9ZCr')
```
The apikey is new and I have no problems with other databases get-id functions. The error message includes "Error in get_csid("3-Cyclohexene-1-methanol,.alpha.,.alpha.,4-trimethyl-, (S)-",  :". Thanks in advance for your orientation.

**Comment by stitam** [comment]
Hi @CesarIsguerra thanks for opening this issue. I could reproduce your output, but I think the returned csid (`NA`) is consistent with the web interface output which also returns zero hits. Do you agree with my assessment?

It seems both the `get_csid()` function in webchem and your apikey is working fine, e.g. `get_csid("caffeine", apikey = 'Lt1Ah22zVgGvn2Lgn2UzH8zSAlnB9ZCr', verbose = TRUE)` returns a valid csid for caffeine, 2424.  Can you please confirm that other compounds work on your end as well?

**Comment by CesarIsguerra** [comment]
Thank you, Tamás, for replying. I've tried the "caffeine" search and still received the "Service not available. Returning NA." message
![imagen](https://user-images.githubusercontent.com/110415031/182485077-0683b719-b5a0-4c7b-aa90-1abccb6c07c1.png)
(Also, the list of substances I first tried get_csid() to search for contained some names that I'm pretty sure ChemSpider would have to acknowledge). So, I understand you did the "caffeine" search with my API key and had success. It makes me wonder: when I tried the initial batch search I inadvertently ran the function without storing the result in a variable and it seemed to be working, so after quite a few minutes (the list's length was ca. 800), when I realized the absence of a storing variable in my command, I stopped execution. Then I retried using a storing variable and the error message came to never leave again (as in the "caffeine" search I did). To make sure it was not a matter of having a worn-out API key, I created a new one (from a new account as well; the one I shared here) with no success. That's when I started this thread. I mention all this because it may mean something to you... or not.

**Comment by stitam** [comment]
Not yet, but I'm working on it :) This error is strange, can you please post your webchem version number (should be 1.1.3) and also check whether `ping_service("cs")` returns TRUE?

**Comment by CesarIsguerra** [comment]
![imagen](https://user-images.githubusercontent.com/110415031/182627559-745c1902-292d-4162-ad9a-d3e0dff8f3cb.png)
![imagen](https://user-images.githubusercontent.com/110415031/182627763-2d92704a-0a99-4ec9-b8e3-96b1a66cd69d.png)
The versions are right but `ping_service("cs")` effectively returns FALSE. There is a problem alright...

**Comment by stitam** [comment]
Okay, I think I have a clue, can you ping the service from a separate network, maybe fire up a vpn if you have one?

**Comment by CesarIsguerra** [comment]
Sorry, I didn't know much about VPNs. I google-searched and activated a free vpn service (Proton) but still got the non-availability error message. I will retry when I'm out of home though, since it may be that some IP address related to me or to my internet service provider was blocked by ChemSpider service, right? Or maybe I'm a little confused aboout what you're suspecting?

**Comment by CesarIsguerra** [comment]
Ok. I'll try the alternatives you mention. Thank you so much for your help, Tamás.
