### ISSUE TITLE
Move from RJSONIO to jsonlite

### ISSUE THREAD

**Issue by kylehamilton** [ropensci/webchem#7]
So according to our packaging guide we're moving from RJSONIO to jsonlite https://github.com/ropensci/packaging_guide#apis

Since the only part of webchem that uses JSON is the Chemical Translation Service would it be ok if I change it over?

**Comment by EDiLD** [comment]
Yeah, go ahead and send a pull request. Note, that there are currently no unit tests in the package (so need to test manuelly).

**Comment by EDiLD** [comment]
Unit tests are no implemented.

**Comment by EDiLD** [comment]
Done via ccf786fe81a184c6d7a45c04f14757e21de063cc.
