### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by EDiLD** [ropensci/webchem#8]
Perhaps on a separate branch to avoid conflicts with CRAN?!

**Comment by sckott** [comment]
what do you mean by avoid conflict with CRAN?

**Comment by EDiLD** [comment]
Tests are run by r cmd check when submitting to cran - if an api is down the tests will fail. We had that also with taxize  - how did we solve it there?

**Comment by sckott** [comment]
ah, i just dont run tests on CRAN, but instead run tests on Travis once daily in addition to on any commits/pull requests/etc. 

I just `.Rbuildignore` tests for the CRAN version, then remove that ignore until the next CRAN version. Alternatively, I think testthat package has a feature to skip on cran, haven't used it yet though

**Comment by EDiLD** [comment]
7099d6b5e782ca5a74e30f2cb6792cc36d019e8e is the last commit in a series of adding test to the package.
